### ISSUE TITLE
Parser fails at `record` used as identifier

### ISSUE THREAD

**Issue by dos65** [paul-hammant/qdox#108]
Input:
```java
package sample;

public interface A
{

   void record();

}
```

Error trace:
```
com.thoughtworks.qdox.parser.ParseException: syntax error @[6,9]
	at com.thoughtworks.qdox.parser.impl.Parser.yyerror(Parser.java:1963)
	at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:2085)
	at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:1944)
	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:232)
	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:190)
	at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:94)
	at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:89)
	at com.thoughtworks.qdox.library.SortedClassLibraryBuilder.addSource(SortedClassLibraryBuilder.java:162)
	at com.thoughtworks.qdox.JavaProjectBuilder.addSource(JavaProjectBuilder.java:174)
```

**Comment by rfscholte** [comment]
most likely fixed with https://github.com/paul-hammant/qdox/commit/c57b152fc8c7b1672a433a271ac59d40cc42812a, please verify

**Comment by dos65** [comment]
> most likely fixed with https://github.com/paul-hammant/qdox/commit/c57b152fc8c7b1672a433a271ac59d40cc42812a, please verify

yep - it was, added my sample as a test and it pass

It would be nice to get a release with this fix
