### ISSUE TITLE
Syntax error @[65,1]

### ISSUE THREAD

**Issue by Senjuti** [paul-hammant/qdox#14]
Hi, 
I'm not able to understand what the following error indicates:
Exception in thread "main" com.thoughtworks.qdox.parser.ParseException: syntax error @[65,1]
	at com.thoughtworks.qdox.parser.impl.Parser.yyerror(Parser.java:1683)
	at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:1805)
	at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:1664)
	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:210)
	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:167)
	at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:94)
	at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:89)
	at com.thoughtworks.qdox.library.SortedClassLibraryBuilder.addSource(SortedClassLibraryBuilder.java:161)

The line which causes the error in my Java program is:
			JavaSource src = builder.addSource(new FileReader(line));
where line is the String name of a path to a class stored on my file system.

**Comment by rfscholte** [comment]
hi, so there seems to be an issue with the content this file, line 65, column 1. If this file can be compiled, then you've probably found an edge case in the syntax which QDox can't handle yet.
If you can provide the part of the content causing the issue, we can have a look at it.
