### ISSUE TITLE
ParseException with an anonymous class as parameter of an enum constructor

### ISSUE THREAD

**Issue by Tunaki** [paul-hammant/qdox#15]
This issue was discovered with the JIRA issue [MPLUGIN-320](https://issues.apache.org/jira/browse/MPLUGIN-320) for the Maven Plugin Plugin, for which it blocks resolution.

Consider the class

```java
package parent;

public enum MyEnum {
    VALUE(new Runnable() {
        @Override
        public void run() { }
    });
    MyEnum(Runnable function) { }
}

```

which uses an anonymous class as a parameter of an enum constructor. The following code:

```java
JavaProjectBuilder builder = new JavaProjectBuilder();
builder.addSource(new File(".../parent/MyEnum.java"));
```

fails with

```
Exception in thread "main" com.thoughtworks.qdox.parser.ParseException: syntax error @[8,15] in file:/C:/.../parent/MyEnum.java
  at com.thoughtworks.qdox.parser.impl.Parser.yyerror(Parser.java:1739)
  at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:1861)
  at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:1720)
  at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:232)
  at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:209)
  at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:157)
  at com.thoughtworks.qdox.library.SortedClassLibraryBuilder.addSource(SortedClassLibraryBuilder.java:173)
  at com.thoughtworks.qdox.JavaProjectBuilder.addSource(JavaProjectBuilder.java:151)
```

The same failure can be caused with a method-reference or a lambda expression (`() -> {}`). Outside of an enum constructor parameter (for example as a field, as a method argument, or as a class constructor parameter), the failure does not occur.

**Comment by rfscholte** [comment]
MPLUGIN-320 was actually an issue regarding methodReferences ( not recognizing the :: separator ). Both are fixed.

**Comment by Tunaki** [comment]
Ah I assumed it was the same bug that caused the behaviour (because method-references worked fine in other contexts). Thanks for fixing the two!

**Comment by RobertKolter** [comment]
Using a lambda expression doesn't work in version 2.0-M9. 

The following class is passed to JavaprojectBuilder.addSource

```java
... // some Imports...
public class ClassToTest {
	public static enum Display {
		LOWVALUE(v -> v.toLowerCase() + "_");

		final Function<String, String> convert;

		private Display(final Function<String, String> convert) {
			this.convert = convert;
		}
	}
}
``` 

This gives
```
Exception in thread "main" com.thoughtworks.qdox.parser.ParseException: syntax error @[8,15] in file:[...]
	at com.thoughtworks.qdox.parser.impl.Parser.yyerror(Parser.java:1775)
	at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:1897)
	at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:1756)
	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:232)
	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:209)
	at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:159)
	at com.thoughtworks.qdox.library.SortedClassLibraryBuilder.addSource(SortedClassLibraryBuilder.java:174)
	at com.thoughtworks.qdox.JavaProjectBuilder.addSource(JavaProjectBuilder.java:151)
```

Is this bug already fixed in some version for the near future? Thanks in advance.

**Comment by rfscholte** [comment]
@RobertKolter please create a new issue. And I can give you a hint how you can help to fix this: [src/grammar/parser.y](https://github.com/paul-hammant/qdox/blob/master/src/grammar/parser.y) contains the parsing code, which is based on the [Java Language Specification](https://docs.oracle.com/javase/specs/jls/se10/html/jls-19.html) I can imagine that lambda's aren't 100% covered yet.

**Comment by RobertKolter** [comment]
I have submitted a new issue as you told: https://github.com/paul-hammant/qdox/issues/50
