### ISSUE TITLE
Syntax error on annotated type parameter

### ISSUE THREAD

**Issue by eskatos** [paul-hammant/qdox#182]
When parsing the following code:

```java
public interface Example<T extends @Nullable Object> {}
```

or any annotated type parameter,
qdox 2.0.3 fails with:

```
Caused by: com.thoughtworks.qdox.parser.ParseException: syntax error @[26,42] in file:/path/to/Example.java
        at com.thoughtworks.qdox.parser.impl.Parser.yyerror(Parser.java:1963)
        at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:2085)
        at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:1944)
        at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:232)
        at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:209)
        at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:159)
```

----

### Context

Parsing Java code from the https://github.com/gradle/gradle codebase for its own build.

Two examples:

https://github.com/gradle/gradle/blob/13c9f3d7a3e7d7a6180fd6bd5c52f35c5d068680/subprojects/core-api/src/main/java/org/gradle/api/Transformer.java#L26

https://github.com/gradle/gradle/blob/13c9f3d7a3e7d7a6180fd6bd5c52f35c5d068680/subprojects/core-api/src/main/java/org/gradle/api/provider/Provider.java#L127

**Comment by eskatos** [comment]
This might be a duplicate of
* https://github.com/paul-hammant/qdox/issues/181

**Comment by paul-hammant** [comment]
Can you make an integration test -> https://github.com/paul-hammant/qdox/tree/master/src/it ?

**Comment by paul-hammant** [comment]
> @paul-hammant if I can raise a PR that contains an integration test, would it be possible to get a fix for this released?

For sure.

**Comment by ascopes** [comment]
Raised GH-271 which reproduces this issue via a Maven Invoker Plugin test.

**Comment by paul-hammant** [comment]
Honestly, give it a go. You're only making a pull-request and I've a
policy on repairing those rather than rejecting them for one small defect

**Comment by ascopes** [comment]
Will take a look when I am next at a PC (out of the country at the moment)

Thanks for the update.

**Comment by ascopes** [comment]
@paul-hammant just got home.

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Protobuf Maven Plugin Parent 3.8.1-SNAPSHOT:
[INFO] 
[INFO] Protobuf Maven Plugin Parent ....................... SUCCESS [  2.448 s]
[INFO] Protobuf Maven Plugin .............................. SUCCESS [ 14.029 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.796 s (Wall Clock)
[INFO] Finished at: 2025-08-22T13:23:15+01:00
[INFO] ------------------------------------------------------------------------
```
looks like your fix worked perfectly ❤️ 

Please could you release a bugfix to Maven Central for this? I can then raise the corresponding paperwork with Apache's Maven plugins to get a fix released on their side that incorporates your fix.

As of right now, the following is working for me though, which is a huge step in the right direction.

```
        <plugin>
          <!-- Generate plugin descriptors. -->
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-plugin-plugin</artifactId>
          <version>${maven-plugin-plugin.version}</version>

          <dependencies>
            <dependency>
              <groupId>com.thoughtworks.qdox</groupId>
              <artifactId>qdox</artifactId>
              <version>2.2.1-SNAPSHOT</version>
            </dependency>
          </dependencies>
        </plugin>
```

**Comment by paul-hammant** [comment]
Won't fix - see main README.md file.
