### ISSUE TITLE
Exception when parsing Enum

### ISSUE THREAD

**Issue by cemo** [paul-hammant/qdox#31]
This seems a new variant of issue #1. I cloned project from the issue #1 and added a sample case to reproduce issue. 

I have tested with both JDK 9 and 8.  (Seems not related to JDK version, but I hit the issue when I was trying to upgrade to JDK9)

Project: https://github.com/cemo/qdox-bug
Test Class: TestEnumsWithFields#testNEnums

Thanks

**Comment by cemo** [comment]
Gentle ping @rfscholte :)

**Comment by rfscholte** [comment]
I can see the failing tests, but have no time to pick this up. Something with Java 9 :)

**Comment by cemo** [comment]
This will be blocker for us since `maven-plugin-plugin` is using qdox and unfortunately we have some plugins requires us to upgrade as well. 

Btw thanks for your time, awesome project.

**Comment by Me1kaa** [comment]
I have an issue with Java8 with enums(QDOX ver:2.0-M7, java: "1.8.0_101").  
Parsing of this code is failing(when i have an array in enum's constructor):
`public enum SomeEnum {
        VALUE1("hello", 1, new String[]{"hello", "world"});

        SomeEnum(String string, int integer, String[] stringArray) {
        }
    }
`

Exception in thread "main" com.thoughtworks.qdox.parser.ParseException: syntax error @[5,53] in file:/${PATH_TO_PROJECT_OMMITTED}/src/main/java/SomeEnum.java
	at com.thoughtworks.qdox.parser.impl.Parser.yyerror(Parser.java:1781)
	at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:1903)
	at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:1762)
	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:232)
	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:209)
	at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:159)
	at com.thoughtworks.qdox.library.SortedClassLibraryBuilder.addSource(SortedClassLibraryBuilder.java:174)
	at com.thoughtworks.qdox.JavaProjectBuilder.addSource(JavaProjectBuilder.java:151)
	at com.thoughtworks.qdox.JavaProjectBuilder$2.visitFile(JavaProjectBuilder.java:224)
	at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:103)
	at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:91)
	at com.thoughtworks.qdox.directorywalker.DirectoryScanner.scan(DirectoryScanner.java:81)
	at com.thoughtworks.qdox.JavaProjectBuilder.addSourceTree(JavaProjectBuilder.java:218)
	at com.thoughtworks.qdox.JavaProjectBuilder.addSourceTree(JavaProjectBuilder.java:205)
If i delete String[] argument - it works fine.

**Comment by cemo** [comment]
Hi @rfscholte, I have to revisit this issue after some time. Would you please cut a release?

**Comment by rfscholte** [comment]
QDox 2.0-M8 is available at Maven Central

**Comment by cemo** [comment]
Thanks
