### ISSUE TITLE
java.lang.NullPointerException when parsing generic method in inner enum

### ISSUE THREAD

**Issue by edwardharks** [paul-hammant/qdox#43]
I'm parsing a directory containing Java source files and I get the following exception:

```
Exception in thread "main" java.lang.NullPointerException
        at com.thoughtworks.qdox.builder.impl.ModelBuilder.createTypeVariable(ModelBuilder.java:503)
        at com.thoughtworks.qdox.builder.impl.ModelBuilder.endMethod(ModelBuilder.java:470)
        at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:2158)
        at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:1732)
        at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:232)
        at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:209)
        at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:159)
        at com.thoughtworks.qdox.library.SortedClassLibraryBuilder.addSource(SortedClassLibraryBuilder.java:174)
        at com.thoughtworks.qdox.JavaProjectBuilder.addSource(JavaProjectBuilder.java:151)
        at com.thoughtworks.qdox.JavaProjectBuilder$2.visitFile(JavaProjectBuilder.java:224)
        at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:103)
        at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:91)
        at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:91)
        at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:91)
        at com.thoughtworks.qdox.directorywalker.DirectoryScanner.scan(DirectoryScanner.java:81)
        at com.thoughtworks.qdox.JavaProjectBuilder.addSourceTree(JavaProjectBuilder.java:218)
        at com.thoughtworks.qdox.JavaProjectBuilder.addSourceTree(JavaProjectBuilder.java:205)
        at com.edwardharker.methodsextractor.MethodsExtractor.parseClasses(MethodsExtractor.kt:20)
        at com.edwardharker.methodsextractor.MethodsExtractor.main(MethodsExtractor.kt:11)

```

This is my code:
```
JavaProjectBuilder builder = new JavaProjectBuilder()
builder.addSourceTree(new File(sourceDir))
```

**Comment by rfscholte** [comment]
The problem is in one of the sourcefiles. Can you bring the issue back to 1 source file and upload that content?

**Comment by edwardharks** [comment]
I've narrowed it down to `java.time.temporal.IsoFields.java`. You can see the source [here](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/time/temporal/IsoFields.java)

**Comment by rfscholte** [comment]
QDox has no problem parsing this file. Is it really this sourcefile or a piece of code where you use IsoFields?

**Comment by edwardharks** [comment]
I'm not using `IsoFields` at all, only trying to parse it. This is the code I have which throws the exception above:
```
public static void main(String[] args) throws FileNotFoundException {
    JavaProjectBuilder builder = new JavaProjectBuilder();
    builder.addSource(new FileReader("/path/to/IsoFields.java"));
}
``` 

I'm using QDox version 2.0-M8

**Comment by rfscholte** [comment]
I've been able to find the troubling part. Here's the minimal code to reproduce the NPE:

    package java.time.temporal;

    public final class IsoFields {

    private static enum Field implements TemporalField {
        DAY_OF_QUARTER {
            public <R extends Temporal> R adjustInto(R temporal, long newValue) {
                return null;
            }
        }
    }
}

**Comment by Klesh-** [comment]
I have the same problem. 2.0-M8
`
public enum AccessorType {

    DEQUE {
        @Override
        <T> void clone(T origin, T result) {
            //...
        }
    }

    abstract <T> void clone(T origin, T result);
}
`

When will you fix this?
Thanks!

**Comment by rfscholte** [comment]
@Klesh- Welcome to the Open Source Community. If you need this to be fixed, then the best you can do is provide a patch yourself. We can review it and apply it when it properly fixes the issue.
