### ISSUE TITLE
Syntax Error when call methods in Enum constuctor

### ISSUE THREAD

**Issue by USK-DIMA** [paul-hammant/qdox#45]
Hello!  I got an exception when I used qdox:

Exception in thread "main" com.thoughtworks.qdox.parser.ParseException: syntax error @[6,43] in file:/E:/username/IdeaProjects/qdoxSimple/src/main/java/ru/uskov/dmitry/qdox/simple/ServiceEnum.java
                at com.thoughtworks.qdox.parser.impl.Parser.yyerror(Parser.java:1751)
                at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:1873)
                at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:1732)
                at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:232)
                at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:209)
                at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:159)
                at com.thoughtworks.qdox.library.SortedClassLibraryBuilder.addSource(SortedClassLibraryBuilder.java:174)
                at com.thoughtworks.qdox.JavaProjectBuilder.addSource(JavaProjectBuilder.java:151)
                at ru.uskov.dmitry.qdox.simple.Main.main(Main.java:14)

This is a problem class:

```
package ru.uskov.dmitry.qdox.simple;

public enum ServiceEnum {

    //FIRST_SERVICE(ServiceBuilder.builder()); //Don't work in 2.0-M4 version, but work in 2.0-M5 and more
    FIRST_SERVICE(ServiceBuilder.builder().someMethod()); //Din't work 

    ServiceEnum(Object x) {
    }


    public static class ServiceBuilder {

        private ServiceBuilder() {
        }

        public static ServiceBuilder builder() {
            return new ServiceBuilder();

        }

        ServiceBuilder someMethod() {
            return this;
        }
    }
}

```

**Comment by rfscholte** [comment]
Cannot reproduce after fixing #47
