### ISSUE TITLE
I don't understand the exception

### ISSUE THREAD

**Issue by Heaminator** [paul-hammant/qdox#51]
I don't understand the exceptions. I read a file, then I get this exception:

```
Exception in thread "main" com.thoughtworks.qdox.parser.ParseException: syntax error @[1,2]
	at com.thoughtworks.qdox.parser.impl.Parser.yyerror(Parser.java:1775)
	at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:1897)
	at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:1756)
	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:232)
	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:190)
	at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:94)
	at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:89)
	at com.thoughtworks.qdox.library.SortedClassLibraryBuilder.addSource(SortedClassLibraryBuilder.java:162)
	at com.thoughtworks.qdox.JavaProjectBuilder.addSource(JavaProjectBuilder.java:174)
	at QDoxExample.main(QDoxExample.java:28)

```

Okay... i understand there was a ParseException. Alright. But why? What does mean "@[1,2]"?

**Comment by rfscholte** [comment]
line 1, column 2

**Comment by Heaminator** [comment]
So... first number descirbes and second number the column - alright thanks
