### ISSUE TITLE
word 'record' is causing an error

### ISSUE THREAD

**Issue by rbrtjr** [paul-hammant/qdox#85]
For some reason the word 'record' is causing an error "Exception in thread "main" com.thoughtworks.qdox.parser.ParseException: syntax error" in all java sources tested.

**Comment by Ziyear** [comment]
```java
        JavaProjectBuilder builder = new JavaProjectBuilder();
        builder.setErrorHandler((e) -> log.warn(e.getMessage()));
``` 
Print the log and replace it with your exception handling logic

**Comment by rbrtjr** [comment]
Hello.
_>>> log.warn(e.getMessage()));  ... >> log? got error..._

In all java files that contained the words 'record, permits' in any identifier the error-result was the same. But replacing 'record' with 'record_', (or 'permits' by 'permits_') the parser accepted. But I only needed information on methods and variables for NLP analysis, So, the result did not change for me.

Error message:

Exception in thread "main" com.thoughtworks.qdox.parser.ParseException: syntax error @[240,17] in file:/E:/Downloads/Share/UNIRIO/DsC/Code/%23packages/apache/apache-ant-1.10.9/src/main/org/apache/tools/ant/taskdefs/optional/unix/Symlink.java
	at com.thoughtworks.qdox.parser.impl.Parser.yyerror(Parser.java:1963)
	at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:2085)
	at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:1944)
	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:232)
	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:209)
	at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:159)
	at com.thoughtworks.qdox.library.SortedClassLibraryBuilder.addSource(SortedClassLibraryBuilder.java:174)
	at com.thoughtworks.qdox.JavaProjectBuilder.addSource(JavaProjectBuilder.java:151)
	at com.thoughtworks.qdox.JavaProjectBuilder$2.visitFile(JavaProjectBuilder.java:224)
	at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:103)
	at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:91)
	at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:91)
	at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:91)
	at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:91)
	at com.thoughtworks.qdox.directorywalker.DirectoryScanner.scan(DirectoryScanner.java:81)
	at com.thoughtworks.qdox.JavaProjectBuilder.addSourceTree(JavaProjectBuilder.java:218)
	at com.thoughtworks.qdox.JavaProjectBuilder.addSourceTree(JavaProjectBuilder.java:205)
	at QDOXScanner.FileElements(QDOXScanner.java:114)
	at QDOXScanner.main(QDOXScanner.java:226)
![Image1](https://user-images.githubusercontent.com/6318971/147682084-2acb8503-cd24-4aa4-847e-bdb5ee999275.png)

**Comment by shalousun** [comment]
Since JDK 14, record has become a JAVA keyword，qdox already supports the new version of jdk, so this keyword will be checked, but qdox has a bug, record can exist as a field name.

**Comment by imndszy** [comment]
I rolled back to qdox 2.0.0 to avoid this bug.

**Comment by rfscholte** [comment]
Should be fixed with https://github.com/paul-hammant/qdox/commit/c887457779b8b3b41a7226147bcd0bd9163161ff, can you verify?

**Comment by rbrtjr** [comment]
> 

Ok. Copied the codes. I will recompile to test.

**Comment by rbrtjr** [comment]
I think it's OK now. I tested it with the sources I used and it didn't show any errors.
